# name of the software
title: Stellantis for Developers
name: Stellantis for Developers
description: Stellantis for Developers is the dedicated platform for application developers working with Stellantis's connected vehicles API and SDKs.
# url: "https://pages.github.psa-cloud.com" # the subpath of the site, e.g. /blog
baseurl: "/p4d00/doc" # the subpath of the site, e.g. /blog

# dev/prod
environment: "prod"

# github links
gitHubURL: "https://github.psa-cloud.com/p4d00/doc/tree/master/"
gitHubSpecB2B: "https://github.psa-cloud.com/mph00/Spec/blob/master/spec/api/b2b/api-b2b.yaml"
gitHubSpecB2C: "https://github.psa-cloud.com/mph00/Spec/blob/master/spec/api/b2c/psacc.yaml"

# doc versionning
doc-version: "10.0.0"

# WEB API BaseURI - theses var have to be renamed without prod/preprod (because we display only one at once)
webapiB2C: "https://api.groupe-psa.com/connectedcar/v4"
cvsOAuth2: "https://idpcvs.{brand.tld}/am/oauth2/access_token"
virtualKeyToken: "https://api.groupe-psa.com/connectedcar/v3"
webapiB2B: "https://api-cert.groupe-psa.com/connectedcar/{version}"
webapiB2Bv3: "https://api-cert.groupe-psa.com/connectedcar/v3"
webapiB2Bv2: "https://api-cert.groupe-psa.com/connectedcar/v2"

collections:
  webportal-nac-reference:
    output: true
    permalink: /webportal/v1/api-reference/:name
  webportal-ivi-public-reference:
    output: true
    permalink: /webportal/v2/api-reference/:name
  mobile-sdk-public-reference:
    output: false
    permalink: /mobile-sdk/references/:name
  mobile-sdk-reference:
    output: true
    permalink: /mobile-sdk/references/:name

exclude:
 - webapi/content/
 - mobile-sdk/content/
 - "node_modules/"
 - "*.gemspec"
 - "*.gem"
 - "Gemfile"
 - "Gemfile.lock"
 - "package.json"
 - "package-lock.json"
 - "script/"
 - "schema/"
 - "LICENSE.txt"
 - "lib/"
 - "bin/"
 - "README.md"
 - "Rakefile"
 
plugins:
  - jekyll-redirect-from

links:
  header:
  footer:

ui:
  header:
      color1: "#080331"
      color2: "#673051"

social:

analytics:

# Build settings
kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
# highlighter: rouge

permalink: pretty

# Enable or disable the site search
search_enabled: true
