# name of the software
title: PSA Groupe for developers
name: PSA Groupe for developers
description: Groupe PSA for Developers is the dedicated platform for application developers working with Groupe PSA's connected vehicles API and SDKs.
baseurl: "" # the subpath of the site, e.g. /blog
url: "https://developer.groupe-psa.io" # the base hostname & protocol for the site, e.g. http://example.com

# github links
gitHubURL: "https://github.com/GroupePSA/groupepsa.github.io/tree/master/"
gitHubSpecB2B: "https://github.com/GroupePSA/groupepsa.github.io/blob/master/assets/openapi/api-b2b-webhook-template.yaml"
gitHubSpecB2C: "https://github.com/GroupePSA/groupepsa.github.io/blob/master/assets/openapi/psacc.yaml"

# doc versionning
doc-version: "7.2.0"

# WEB API BaseURI - theses var have to be renamed without prod/preprod (because we display only one at once)
webapiB2C: "https://api.groupe-psa.com/connectedcar/v4"
cvsOAuth2: "https://idpcvs.{brand.tld}/am/oauth2/access_token"
virtualKeyToken: "https://api.groupe-psa.com/connectedcar/v3"
webapiB2B: "https://api-cert.groupe-psa.com/connectedcar/{version}"
webapiB2Bv3: "https://api-cert.groupe-psa.com/connectedcar/v3"
webapiB2Bv2: "https://api-cert.groupe-psa.com/connectedcar/v2"

collections:
  webportal-nac-reference:
    output: false
  webportal-ivi-reference:
    output: false
  apis-data:
    output: true

exclude:
 - webapi/content/
 - mobile-sdk/content/
 - "node_modules/"
 - "*.gemspec"
 - "*.gem"
 - "Gemfile"
 - "Gemfile.lock"
 - "package.json"
 - "package-lock.json"
 - "script/"
 - "schema/"
 - "LICENSE.txt"
 - "lib/"
 - "bin/"
 - "README.md"
 - "Rakefile"
 - "terms-of-use.md"

plugins:
  - jekyll-redirect-from

links:
    header:
    footer:

ui:
    header:
        color1: "#080331"
        color2: "#673051"

social:

analytics:

# Build settings
markdown: kramdown
highlighter: rouge

permalink: pretty

# Enable or disable the site search
search_enabled: true
