# name of the software
title: Stellantis for Developers
name: Stellantis for Developers
description: Stellantis for Developers is the dedicated platform for application developers working with Stellantis's connected vehicles API and SDKs.
baseurl: "" # the subpath of the site, e.g. /blog
url: "https://developer.groupe-psa.io" # the base hostname & protocol for the site, e.g. http://example.com

# github links
gitHubURL: "https://github.psa-cloud.com/p4d00/doc/tree/master/"
gitHubSpecB2B: "https://github.psa-cloud.com/mph00/Spec/blob/master/spec/api/b2b/api-b2b.yaml"
gitHubSpecB2C: "https://github.psa-cloud.com/mph00/Spec/blob/master/spec/api/b2c/psacc.yaml"
gitHubMasterPath: "/blob/master/"

# doc versionning
doc-version: "13.0.0"

# WEB API BaseURI - theses var have to be renamed without prod/preprod (because we display only one at once)
webapiB2C: "https://api-cert.groupe-psa.com/connectedcar/v4"
webapiB2B: "https://api-cert.groupe-psa.com/connectedcar/v3"
cvsOAuth2: "https://idpcvs.{brand.tld}/am/oauth2"
virtualKeyToken: "https://api.groupe-psa.com/connectedcar/v3"

plugins:
  - jekyll-redirect-from

collections:
  webportal-nac-reference:
    output: true
    permalink: /webportal/v1/api-reference/:name
  webportal-ivi-public-reference:
    output: true
    permalink: /webportal/v2/api-reference/:name

exclude:
 - webapi/content/
 - "node_modules/"
 - "*.gemspec"
 - "*.gem"
 - "Gemfile"
 - "Gemfile.lock"
 - "package.json"
 - "package-lock.json"
 - "script/"
 - "schema/"
 - "LICENSE.txt"
 - "lib/"
 - "bin/"
 - "README.md"
 - "Rakefile"

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: true
permalink: pretty
search_enabled: true